import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/utils/supabase/server'
import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(req: NextRequest) {
  try {
    const { complaint, category } = await req.json()

    if (!complaint?.trim()) {
      return NextResponse.json(
        { error: 'Please write something' }, 
        { status: 400 }
      )
    }

    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) {
      return NextResponse.json(
        { error: 'Unauthorized' }, 
        { status: 401 }
      )
    }

    const { data: profile } = await supabase
      .from('profiles')
      .select('full_name, email')
      .eq('id', user.id)
      .single()

    // Save to DB
    const { error: dbError } = await supabase.from('roasts').insert({
      user_id: user.id,
      user_email: profile?.email || user.email,
      user_name: profile?.full_name || 'Anonymous',
      original_complaint: complaint,
      category: category || 'general',
    })

    if (dbError) throw dbError

    // Send email to owner
    if (process.env.OWNER_NOTIFICATION_EMAIL) {
      await resend.emails.send({
        from: 'FlashTTS Feedback <noreply@flashtts.com>',
        to: process.env.OWNER_NOTIFICATION_EMAIL,
        subject: `💬 New Feedback from ${profile?.full_name || user.email}`,
        html: `
          <div style="font-family: sans-serif; 
            max-width: 600px; margin: 0 auto; 
            padding: 24px; background: #fff; border: 1px solid #eee; border-radius: 12px;">
            
            <h2 style="color: #E8522A; margin: 0 0 24px;">
              💬 New User Feedback
            </h2>

            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 10px 0; color: #999; width: 100px; font-size: 13px; border-bottom: 1px solid #f5f5f5;">From</td>
                <td style="padding: 10px 0; font-weight: 700; font-size: 13px; border-bottom: 1px solid #f5f5f5;">
                  ${profile?.full_name || 'Anonymous'}
                </td>
              </tr>
              <tr>
                <td style="padding: 10px 0; color: #999; font-size: 13px; border-bottom: 1px solid #f5f5f5;">Email</td>
                <td style="padding: 10px 0; font-size: 13px; color: #E8522A; border-bottom: 1px solid #f5f5f5;">
                  ${profile?.email || user.email}
                </td>
              </tr>
              <tr>
                <td style="padding: 10px 0; color: #999; font-size: 13px; border-bottom: 1px solid #f5f5f5;">Category</td>
                <td style="padding: 10px 0; font-size: 13px; border-bottom: 1px solid #f5f5f5;">
                  ${category || 'General'}
                </td>
              </tr>
            </table>

            <div style="background: #fdf2f0; 
              border-left: 4px solid #E8522A;
              border-radius: 8px; 
              padding: 20px; margin: 32px 0;">
              <p style="margin: 0 0 10px; 
                font-size: 11px; color: #E8522A; 
                text-transform: uppercase; 
                letter-spacing: 1.5px; font-weight: 700;">
                Feedback Message
              </p>
              <p style="margin: 0; font-size: 16px; 
                line-height: 1.7; color: #222;">
                ${complaint}
              </p>
            </div>

            <p style="color: #999; font-size: 12px; text-align: center; margin-top: 32px;">
              Generated by FlashTTS Feedback System
            </p>
          </div>
        `
      })
    }

    return NextResponse.json({ success: true })
  } catch (error: any) {
    console.error('[FEEDBACK_API_ERROR]', error)
    return NextResponse.json({ error: 'Failed to send feedback' }, { status: 500 })
  }
}
